export const PRODUCTLOADING="PRODUCTLOADING"
export const PRODUCTFAILED="PRODUCTFAILED"
export const GETALLPRODUCTSSUCCESS="GETALLPRODUCTSSUCCESS"
export const GETONEPRODUCTSUCCESS="GETONEPRODUCTSUCCESS"
